dbt-postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: public
      threads: 3
      keepalives_idle: 0 # default 0, indicating the system default